repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
