name: Python Tox

on:
  push:
    paths:
      '**.py'
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        pycldf: ["1.24.0", "1.21.0", "NEWEST"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install pycldf ${{ matrix.pycldf }}
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox codecov
        if [ x${{ matrix.pycldf }} == xNEWEST ]
        then
          pip install pycldf
        else
          pip install pycldf==${{ matrix.pycldf }}
        fi
    - name: Install other dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install catalogs
      run: |
        mkdir -p ~/.config/cldf/
        (cd ~/.config/cldf/ && [ -d glottolog ] || git clone --depth 1 https://github.com/glottolog/glottolog.git)
        (cd ~/.config/cldf/ && [ -d concepticon-data ] || git clone --depth 1 https://github.com/concepticon/concepticon-data.git concepticon)
        (cd ~/.config/cldf/ && [ -d clts ] || git clone -b v2.0.0 --depth 1 https://github.com/cldf-clts/clts.git)
        pip install cldfbench pyglottolog pyconcepticon pyclts
        cldfbench catconfig
        cldfbench catinfo
    - name: Test with tox
      run: |
        tox
        codecov
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
